SDKS-965 Support Apple SignIn
ForgeRock/forgerock-android-sdk pull request #104
Opened 2021-04-27 19:39 UTC by witrisna

2021-04-28 16:01 UTC, spetrov requested changes
Looks good to me! 👍 
I have a few minor questions. Please take a look.

2021-04-28 16:12 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/AuthServiceClient.java
> +import org.forgerock.android.auth.callback.AdditionalParameterCallback;
Update copyright

2021-04-28 16:28 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
> +    public CustomTabsIntent.Builder getIntentBuilder(AuthorizationService service, Uri uri) {
javadoc?

2021-04-28 16:34 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/FacebookSignInHandler.java
extra line

2021-04-28 16:36 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/IdPResult.java
> +    public IdPResult(String token, Map<String, String> additionalParameters) {
javadoc?

2021-04-28 16:36 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/IdPResult.java
> +    public IdPResult(String token) {
javadoc?

2021-04-28 17:19 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/AuthServiceClient.java
> +import org.forgerock.android.auth.callback.AdditionalParameterCallback;
Updated

2021-04-28 17:22 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
> +                .setResponseMode(FORM_POST);
Similar to above issue, that attribute does not include in the IdPCallback

2021-04-28 17:22 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
> +    public static final String TOKEN_ENDPOINT = "https://appleid.apple.com/auth/token";
Currently, the IdPCallback does not include the authorization and token endpoint. That may need to change the server to return those values, another option is to use well-known endpoint. I would keep it hardcode for now.

2021-04-28 17:22 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
> +    public static final String AUTHORIZE_ENDPOINT = "https://appleid.apple.com/auth/authorize";
Currently, the IdPCallback does not include the authorization and token endpoint. That may need to change the server to return those values, another option is to use well-known endpoint. I would keep it hardcode for now.

2021-04-28 17:43 UTC, spetrov commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
> +    public static final String AUTHORIZE_ENDPOINT = "https://appleid.apple.com/auth/authorize";
sounds good! 👍

2021-04-28 17:43 UTC, spetrov commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
> +                .setResponseMode(FORM_POST);
👍

2021-04-28 22:02 UTC, spetrov approved these changes
Looks good to me! 👍 
Approved!

2021-05-04 18:40 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/IdPResult.java
> +    public IdPResult(String token, Map<String, String> additionalParameters) {
Updated

2021-05-04 18:40 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/idp/IdPResult.java
> +    public IdPResult(String token) {
Updated

2021-05-04 18:49 UTC, rodrigoareis approved these changes
Looks good to me

2021-05-04 19:02 UTC, merged