SDKS-1403 Sample App for Documentation
ForgeRock/forgerock-android-sdk pull request #137
Opened 2021-12-02 21:49 UTC by witrisna

2021-12-22 20:09 UTC, spetrov submitted a review, later dismissed
I tried the sample app and it looks good to me! 👍🏻

2021-12-23 17:19 UTC, rodrigoareis requested changes
Looks good to me. Minor copyright issues.

2021-12-23 17:19 UTC, rodrigoareis commented on samples/quickstart/src/main/java/org/forgerock/quickstart/NodeDialogFragment.java
> + * Copyright (c) 2020 ForgeRock. All rights reserved.
2021?

2021-12-23 17:19 UTC, rodrigoareis commented on samples/quickstart/src/main/res/layout/fragment_node.xml
> +  ~ Copyright (c) 2020 ForgeRock. All rights reserved.
2021?

2022-01-04 18:57 UTC, witrisna commented on samples/quickstart/src/main/java/org/forgerock/quickstart/NodeDialogFragment.java
> + * Copyright (c) 2020 ForgeRock. All rights reserved.
Updated.

2022-01-04 18:57 UTC, witrisna commented on samples/quickstart/src/main/res/layout/fragment_node.xml
> +  ~ Copyright (c) 2020 ForgeRock. All rights reserved.
Updated

2022-01-06 22:12 UTC, spetrov approved these changes

2022-01-07 01:40 UTC, spetrov approved these changes

2022-01-07 01:45 UTC, merged