SDKS-1408 Discrepancies between Android and iOS behavior upon registering OATH account (Issuer param)
ForgeRock/forgerock-android-sdk pull request #161
Opened 2022-05-12 22:23 UTC by rodrigoareis

# JIRA Ticket

[SDKS-1408](https://bugster.forgerock.org/jira/browse/SDKS-1408) Discrepancies between Android and iOS behavior upon registering OATH account (Issuer param)

# Description

While registering a new mechanism, if "issuer" is empty on the query parameter of the URI, but available in the path, the SDK should not throw exception. Instead, it should use the issue in the path.

# Definition of Done Checklist:

- [x] Acceptance criteria is met.
- [x] All tasks listed in the user story have been completed.
- [x] Coded to standards.
- [x] Ensure backward compatibility.
- [x] API reference docs is updated.
- [x] Unit tests are written.
- [ ] Integration tests are written.
- [ ] e2e tests are written.
- [ ] Functional spec is written/updated.
- [ ] contains example code snippets.
- [ ] Change log updated.
- [ ] Documentation story is created and tracked.
- [ ] Tech debts and remaining tasks are tracked in separated ticket(s).

2022-05-13 22:42 UTC, spetrov approved these changes
Looks good to me! 
I tested the fix using the steps from the problem description in SDKS-1408 and confirmed that the issue no longer occurs... i.e. when "issuer" is empty on the query parameter of the URI but available in the path, the SDK no longer throws an exception.

2022-05-16 16:37 UTC, jeyanthanperiyasamy commented on forgerock-authenticator/src/main/java/org/forgerock/android/auth/MechanismParser.java
> +                if (split[0].equals(ISSUER) && split[1].isEmpty()) {
can we also check  if(split != null && split.length > 1) for safer size to avoid index out of bounds

2022-05-16 16:43 UTC, jeyanthanperiyasamy commented on forgerock-authenticator/src/main/java/org/forgerock/android/auth/MechanismParser.java
> +                if (split[0].equals(ISSUER) && split[1].isEmpty()) {
can we check this as well  - if (split != null && split.length > 1) . just for safer side to avoid index out of bounds

2022-05-16 16:44 UTC, jeyanthanperiyasamy requested changes
minor

2022-05-16 17:04 UTC, jeyanthanperiyasamy approved these changes

2022-05-16 19:16 UTC, merged