SDKS-2097 Fix Google dependency vulnerabilities in the SDK
ForgeRock/forgerock-android-sdk pull request #195
Opened 2022-09-06 20:33 UTC by witrisna

# JIRA Ticket
[SDKS-2097](https://bugster.forgerock.org/jira/browse/SDKS-2097)

# Description
Even upgrading to the latest dependency libraries from Google, Google libraries still depend on order version of  'com.google.android.gms:play-services-basement', to resolve the vulnerabilities issue, explicitly include the latest version of  'com.google.android.gms:play-services-basement:18.1.0' is required
Briefly describe the change and any information that would help speedup the review and testing.

The following components have been tested with the upgraded Google Libraries:

- Captcha Node
- Capture Device Location
- Social Login with Google
- Centralize Login

# Definition of Done Checklist:

- [ ] Acceptance criteria is met.
- [ ] All tasks listed in the user story have been completed.
- [ ] Coded to standards.
- [ ] Ensure backward compatibility.
- [ ] API reference docs is updated.
- [ ] Unit tests are written.
- [ ] Integration tests are written.
- [ ] e2e tests are written.
- [ ] Functional spec is written/updated.
- [ ] contains example code snippets.
- [ ] Change log updated.
- [ ] Documentation story is created and tracked.
- [ ] Tech debts and remaining tasks are tracked in separated ticket(s).

2022-09-07 16:00 UTC, spetrov approved these changes
LGTM 👍🏻

2022-09-07 16:08 UTC, rodrigoareis requested changes
Changes looks good to me. Just missing few header updates

2022-09-07 16:08 UTC, rodrigoareis commented on forgerock-auth-ui/build.gradle
> -    compileOnly 'com.google.android.gms:play-services-fido:18.1.0'
Update copyright

2022-09-07 16:08 UTC, rodrigoareis commented on forgerock-auth/src/test/java/org/forgerock/android/auth/SocialLoginTest.java
> +        SignInCredential signInCredential = new SignInCredential("1234", "", "", "", null, "", "dummy_id_token", "");
Update copyright

2022-09-07 16:08 UTC, rodrigoareis commented on samples/authenticator/build.gradle
> +    implementation "com.google.firebase:firebase-messaging:23.0.8"
Update copyright

2022-09-08 16:02 UTC, spetrov approved these changes

2022-09-08 16:08 UTC, merged