SDKS 2123 - KDOC-  Do not merge - Still under development
ForgeRock/forgerock-android-sdk pull request #223
Opened 2023-01-11 22:49 UTC by jeyanthanperiyasamy

# JIRA Ticket

Please link jira ticket here

# Description

Briefly describe the change and any information that would help speedup the review and testing.

# Definition of Done Checklist:

- [ ] Acceptance criteria is met.
- [ ] All tasks listed in the user story have been completed.
- [ ] Coded to standards.
- [ ] Ensure backward compatibility.
- [ ] API reference docs is updated.
- [ ] Unit tests are written.
- [ ] Integration tests are written.
- [ ] e2e tests are written.
- [ ] Functional spec is written/updated.
- [ ] contains example code snippets.
- [ ] Change log updated.
- [ ] Documentation story is created and tracked.
- [ ] Tech debts and remaining tasks are tracked in separated ticket(s).

2023-01-16 19:30 UTC, rodrigoareis commented on config/kdoc.gradle
> + * Copyright (c) 2021 - 2023 ForgeRock. All rights reserved.
Copyright (c) 2023 ForgeRock. All rights reserved.

2023-01-16 19:31 UTC, rodrigoareis requested changes
Changes looks good. Just a minor change required.

2023-01-18 00:22 UTC, rodrigoareis approved these changes
Changes looks good to me

2023-01-24 00:10 UTC, spetrov approved these changes

2023-01-24 00:11 UTC, merged