Sdks 2334
ForgeRock/forgerock-android-sdk pull request #244
Opened 2023-02-22 10:35 UTC by forgerock-chris

# JIRA Ticket

[SDKS-2334](https://bugster.forgerock.org/jira/browse/SDKS-2334)

# Description

**Problem description:** 

[SDKS-2123](https://bugster.forgerock.org/jira/browse/SDKS-2123) provided the foundation of the kdoc kotlin docs generation (gradle tasks etc...). 
The generated docs however needs to be customized - i.e. use ForgeRock logo/favicon, footer, etc... 

**Acceptance criteria:** 

The generated kdocs uses ForgeRock branding (Logo, footer, navigation area)

**Notes:**

See https://kotlinlang.org/docs/dokka-html.html#configuration

# Definition of Done Checklist:

- [ ] Acceptance criteria is met.
- [ ] All tasks listed in the user story have been completed.
- [ ] Coded to standards.
- [ ] Ensure backward compatibility.
- [ ] API reference docs is updated.
- [ ] Unit tests are written.
- [ ] Integration tests are written.
- [ ] e2e tests are written.
- [ ] Functional spec is written/updated.
- [ ] contains example code snippets.
- [ ] Change log updated.
- [ ] Documentation story is created and tracked.
- [ ] Tech debts and remaining tasks are tracked in separated ticket(s).

2023-02-22 15:37 UTC, jeyanthanperiyasamy commented on build.gradle
> -        jcenter()
Jcenter repositorties are deprecated , so using mavencentral is fine. But @spetrov  keep an eye this when you release ....

2023-02-22 15:38 UTC, jeyanthanperiyasamy commented on dokka/templates/base.ftl
> +<#import "page_metadata.ftl" as page_metadata>
add copyright

2023-02-22 15:39 UTC, jeyanthanperiyasamy commented on dokka/templates/page_metadata.ftl
> +<#macro display>
add copyright

2023-02-22 15:40 UTC, jeyanthanperiyasamy requested changes
add copyright ..everything else looks good for styling

2023-02-23 11:35 UTC, forgerock-chris commented on dokka/templates/base.ftl
> +<#import "page_metadata.ftl" as page_metadata>
DOne.

2023-02-23 11:36 UTC, forgerock-chris commented on dokka/fr-backstage-styles.css
> +:root {
Done.

2023-02-27 17:25 UTC, spetrov approved these changes
Looks great! 👍🏻

2023-02-27 17:28 UTC, merged