SDKS-2445_Updates to NetworkCollector
ForgeRock/forgerock-android-sdk pull request #253
Opened 2023-04-25 11:05 UTC by george-bafaloukas-forgerock

Updated NetworkCollector to include a more complete network connectivity test

# JIRA Ticket
[SDKS-2445](https://bugster.forgerock.org/jira/browse/SDKS-2445)

2023-04-25 13:24 UTC, jeyanthanperiyasamy commented on samples/quickstart/src/main/AndroidManifest.xml
> +        <activity
do we need this ResetActivity in the manifest?

2023-04-25 13:27 UTC, jeyanthanperiyasamy commented on samples/quickstart/src/main/AndroidManifest.xml
> -<!--
Also add the copy right with 2023

2023-04-25 13:28 UTC, jeyanthanperiyasamy commented on samples/quickstart/src/main/AndroidManifest.xml
> -    <!--
please add this comment back, this is for our security tools and folks

2023-04-25 13:37 UTC, jeyanthanperiyasamy reviewed
added few comments

2023-04-27 15:59 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/collector/NetworkCollector.java
> +import android.net.ConnectivityManager;
Update copyright

2023-04-27 16:02 UTC, rodrigoareis requested changes
Changes looks good. Just minor changes required already spotted by Jey

2023-04-27 20:39 UTC, spetrov requested changes
Please, update CHANGELOG.md as well.

2023-05-04 17:05 UTC, rodrigoareis approved these changes
Changes looks good to me

2023-05-04 17:34 UTC, jeyanthanperiyasamy approved these changes
approved

2023-05-04 18:21 UTC, merged