SDKS-2948 crash fix and improvement
ForgeRock/forgerock-android-sdk pull request #390
Opened 2024-01-30 17:36 UTC by jeyanthanperiyasamy

# JIRA Ticket

Please link jira ticket here

# Description

Briefly describe the change and any information that would help speedup the review and testing.

2024-02-01 22:40 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/BiometricBindingHandler.kt
>  import androidx.biometric.BiometricPrompt.CryptoObject
Update copyright

2024-02-01 22:42 UTC, rodrigoareis commented on forgerock-core/src/main/java/org/forgerock/android/auth/biometric/BiometricAuth.kt
> +    ) {
Update copyright

2024-02-01 22:52 UTC, rodrigoareis requested changes
Changes looks good. Just need to update the copyright

2024-02-02 19:10 UTC, jeyanthanperiyasamy commented
Addresses the comments

2024-02-02 20:09 UTC, spetrov approved these changes
Looks good to me!

2024-02-02 21:21 UTC, rodrigoareis approved these changes
Changes looks good to me

2024-02-05 16:02 UTC, merged