PingProtect Implementation
ForgeRock/forgerock-android-sdk pull request #391
Opened 2024-01-31 14:31 UTC by jeyanthanperiyasamy

# JIRA Ticket

Please link jira ticket here

# Description

Briefly describe the change and any information that would help speedup the review and testing.

2024-02-05 04:52 UTC, jeyanthanperiyasamy commented on forgerock-auth/build.gradle
> -    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutine_version"
we dont need this anymore ..all the coroutines are part of `org.jetbrains.kotlinx:kotlinx-coroutines-android:`

2024-02-05 04:53 UTC, jeyanthanperiyasamy commented on build.gradle
> -    repositories {
moved all the repositories to settings.xml . @spetrov we may need to test the maven release to make sure this change works

2024-02-05 04:54 UTC, jeyanthanperiyasamy commented on gradle.properties
> -android.defaults.buildfeatures.buildconfig=true
this is deprecated , so moved this buildconfig to build.gradle

2024-02-05 18:06 UTC, witrisna approved these changes
Looks good to me, minor comment for the sample App.

2024-02-05 18:06 UTC, witrisna commented on samples/app/src/main/java/com/example/app/env/EnvViewModel.kt
> +        CoroutineScope(Dispatchers.Default).launch {
May remove this from the sample, what about create another navigation menu to initialize the Protect SDK?

2024-02-05 20:45 UTC, spetrov reviewed
Looks good to me! 👍🏻

2024-02-06 01:04 UTC, rodrigoareis requested changes
Changes looks good. Minor comments to be addressed.

2024-02-06 01:04 UTC, rodrigoareis commented on samples/app/build.gradle
> +        buildConfig true
Update copyright

2024-02-06 01:04 UTC, rodrigoareis commented on samples/app/src/main/java/com/example/app/env/EnvViewModel.kt
> +import kotlinx.coroutines.CoroutineScope
Update copyright

2024-02-06 01:04 UTC, rodrigoareis commented on samples/app/src/main/java/com/example/app/journey/Journey.kt
> +import com.example.app.callback.PingOneProtectEvaluationCallback
Update copyright

2024-02-06 01:04 UTC, rodrigoareis commented on samples/auth/build.gradle
> +    buildFeatures {
Update copyright

2024-02-06 01:04 UTC, rodrigoareis commented on samples/authenticator/build.gradle
> +        compose true
Update copyright

2024-02-07 16:12 UTC, jeyanthanperiyasamy commented
comments addressed .

2024-02-07 17:28 UTC, spetrov approved these changes

2024-02-07 23:48 UTC, witrisna approved these changes

2024-02-07 23:50 UTC, rodrigoareis approved these changes
Changes looks good to me

2024-02-21 03:02 UTC, spetrov requested changes

2024-02-21 20:41 UTC, merged