Make ActivityNotFoundException to be intercepted by FRListener
ForgeRock/forgerock-android-sdk pull request #404
Opened 2024-03-20 20:16 UTC by MAKARD

# JIRA Ticket

N/A

# Description

Hello Forgerock team!

On our project, we've encountered an issue when android app is crashing with the following stack trace:
```
android.content.ActivityNotFoundException
  at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:555)
  at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:390)
  at org.forgerock.android.auth.AppAuthFragment.onCreate(AppAuthFragment.java:90)
  at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
  at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
  at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
  at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
  at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
  at android.os.Handler.handleCallback(Handler.java:942)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at android.app.ActivityThread.main(ActivityThread.java:8762)
  at java.lang.reflect.Method.invoke(Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

We still don't know the exact root cause of the crash, but we were able to reproduce it by removing/disabling all installed browsers(I appreciate that it's unlikely the real cause thought)

The changes I made are most probably not the right way to fix the problem, but at least it should allow to handle the exception gracefully.

Ideally(for our particular case), it should be: exception intercepted -> try to open an external browser to proceed with centralized login.

Therefore, I also have a question: Is it possible to get the built URL that should be opened in the browser? Since we have a react-native app and custom JS wrapper around FR SDK, it would be convenient to send the callback, like "onFailedToOpenCustomTabs," with the URL to be opened as an argument.

Thanks

2024-03-21 00:33 UTC, witrisna commented
Hi @MAKARD 

Thanks for your contribution to the source. Your help is greatly appreciated.
The SDK is trying to send an Intent to the Android Platform and look for Activity (In this case Browser) to launch the URL, in this situation, there is no browser that can open the URL, by returning the URL to the caller, since there is no Browser available, how can you launch the URL?

Thank you again for your contribution.

Andy

2024-03-21 09:10 UTC, MAKARD commented
Hi @witrisna 

Yes, in the absence of a browser, there is no sense in opening an external browser.
We think it's not the actual case, but rather just one of the possible steps to reproduce, and the exception occurs for some other reason.

2024-03-26 16:47 UTC, witrisna requested changes

2024-03-26 18:39 UTC, MAKARD commented on forgerock-auth/src/main/java/org/forgerock/android/auth/AppAuthFragment.java
> +                Listener.onException(browser.listener, e);
Thanks for the feedback, added the changes

2024-03-26 19:54 UTC, spetrov approved these changes

2024-03-26 19:55 UTC, merged