SDKS-3104 - Improvements in caching the key reference
ForgeRock/forgerock-android-sdk pull request #409
Opened 2024-04-15 05:28 UTC by jeyanthanperiyasamy

# JIRA Ticket

Please link jira ticket here

# Description

Briefly describe the change and any information that would help speedup the review and testing.

2024-04-16 21:55 UTC, witrisna requested changes

2024-04-16 21:55 UTC, witrisna commented on forgerock-core/src/main/java/org/forgerock/android/auth/AndroidMEncryptor.kt
> +        keyStore.deleteEntry(keyAlias)
Shoud we remove the cache also?

2024-04-16 23:38 UTC, jeyanthanperiyasamy commented on forgerock-core/src/main/java/org/forgerock/android/auth/AndroidMEncryptor.kt
> +        keyStore.deleteEntry(keyAlias)
yes good point

2024-04-17 00:11 UTC, witrisna approved these changes

2024-04-17 18:26 UTC, rodrigoareis submitted a review, later dismissed
Changes looks good to me

2024-04-24 15:21 UTC, spetrov submitted a review, later dismissed

2024-04-24 15:43 UTC, spetrov submitted a review, later dismissed

2024-04-24 15:48 UTC, spetrov approved these changes

2024-04-24 15:57 UTC, merged