SDKS-3022 OIDC ping discovery
ForgeRock/forgerock-android-sdk pull request #420
Opened 2024-06-04 16:37 UTC by jeyanthanperiyasamy

# JIRA Ticket

Please link jira ticket here

# Description

Briefly describe the change and any information that would help speedup the review and testing.

2024-06-04 16:55 UTC, witrisna requested changes

2024-06-04 16:55 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
> +            suspendCancellableCoroutine { continuation ->
I think we don't need to use suspendCancellableCoroutine, may just invoke httpClient.newCall().execute?

2024-06-04 16:55 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
> +                        this@FROptions.urlPath.authorizeEndpoint =
Can we keep FROptions immutable?
Clone the existing FROptions and replace the urlPath?
Something like this:
```kotlin
 suspend fun discover(discoverUrl: String) : FROptions {
        // Fetch the new UrlPath from the discoverUrl...
        val newUrlPath = UrlPath() // Replace this with the actual UrlPath fetched from the discoverUrl

        // Create a copy of the current FROptions object and modify the urlPath
        return this.copy(urlPath = newUrlPath)
    }
```

2024-06-04 16:55 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
> +                   var tokenEndpoint: String? = null,
Not sure if we can keep it immutable.

2024-06-04 16:55 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/String+Extension.kt
> +        uri.isAbsolute && uri.scheme != null && uri.host != null
Calling isAbsolute is enough?
Does isAbsolute check the scheme?

2024-06-04 16:55 UTC, witrisna commented on samples/app/src/main/java/com/example/app/AppDrawer.kt
> +        NavigationDrawerItem(
Instead of adding a new navigation drawer, can we enhance com.example.app.env.EnvViewModel to support discover.

2024-06-05 20:02 UTC, witrisna requested changes

2024-06-05 20:02 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
> +            .timeUnit(TimeUnit.SECONDS)
Why we need to set the timeUnit?

2024-06-05 20:12 UTC, jeyanthanperiyasamy commented on forgerock-core/src/main/java/org/forgerock/android/auth/KotlinExtensions.kt
> +            uri.isAbsolute && uri.scheme != null && uri.host != null
https://github.com/ForgeRock/forgerock-android-sdk/pull/420/files/c404174ba7b08a69b77c6f9bf8df3ae7142537f7#diff-84c9dad9fe7bf6d6d407d8388065f00d49e0d35d71e411084eeaf4522fdbbaeb

isabsolute checks the scheme as per the scheme...but it also checks the host ..See if this tests covers all the cases

2024-06-05 20:18 UTC, jeyanthanperiyasamy commented on forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
> +            .timeUnit(TimeUnit.SECONDS)
not required ,,,copt paste error

2024-06-05 20:19 UTC, jeyanthanperiyasamy commented on samples/app/src/main/java/com/example/app/centralize/CentralizeLoginViewModel.kt
> +                val option = options.discover(options.server.url + "/.well-known/openid-configuration")
yes i moved that ..i kind of want you see , what you think.

2024-06-05 23:14 UTC, witrisna requested changes

2024-06-05 23:14 UTC, witrisna commented on samples/app/src/main/java/com/example/app/env/EnvViewModel.kt
> +        if(options.server.url.contains("pingone")) {
Using viewModelScope

2024-06-05 23:14 UTC, witrisna commented on samples/app/src/main/java/com/example/app/centralize/Centralize.kt
> -
Should rollback Centralize  and CentraliszeLoginViewModel?

2024-06-06 14:48 UTC, witrisna approved these changes

2024-06-06 19:50 UTC, vahancouver approved these changes
Changes look good. 

My only concern that we removed some validation along with their tests.
Is this actually necessary now that you have default Server value and setting the url from issuer field?!

2024-06-06 20:18 UTC, jeyanthanperiyasamy commented
My concern is if I keep the validation the realm and cookies have a default values now . But for ping users they can also override that and set that to empty. So it will blow the validation . We assume url will always be there with the issuer, but they can override that as well. So either you do only if all are mandatory or don’t do it

2024-06-10 16:19 UTC, spetrov submitted a review, later dismissed

2024-06-10 18:34 UTC, rodrigoareis commented on samples/app/src/main/java/com/example/app/AppNavHost.kt
> +            val envViewModel: EnvViewModel = viewModel<EnvViewModel>()
Update copyright

2024-06-10 18:35 UTC, rodrigoareis commented on forgerock-core/src/main/java/org/forgerock/android/auth/KotlinExtensions.kt
> +fun String?.isAbsoluteUrl(): Boolean {
Doc?

2024-06-10 18:35 UTC, rodrigoareis reviewed
Overall changes looks good! Two minor comments to address

2024-06-10 18:58 UTC, jeyanthanperiyasamy commented
> Overall changes looks good! Two minor comments to address

Done

2024-06-10 19:42 UTC, rodrigoareis approved these changes
LGTM

2024-06-10 22:38 UTC, witrisna submitted a review, later dismissed

2024-06-11 17:32 UTC, closed without merging