SDKS-3408 Self device management implementation
ForgeRock/forgerock-android-sdk pull request #458
Opened 2024-10-09 19:00 UTC by witrisna

# JIRA Ticket

[SDKS-3408](https://pingidentity.atlassian.net/browse/SDKS-3408)

# Description

Self Device Management Service
```kotlin
val oathDevices: List<OathDevice> = userRepository.oathDevice()
val pushDevices: List<PushDevice> = userRepository.pushDevice()
val webAuthnDevices: List<WebAuthnDevice> = userRepository.webAuthnDevice()
val bindingDevice: List<BindingDevice> = userRepository.bindingDevice()
val profileDevice: List<ProfileDevice> = userRepository.profileDevice()

//Update Device Name
webAuthnDevices[0].deviceName = "New Device Name"
userRepository.update(webAuthnDevices[0])

//Delete Device
userRepository.delete(webAuthnDevices[0])
```

Sample App Update:
![CleanShot 2024-10-09 at 11 58 27@2x](https://github.com/user-attachments/assets/576a5165-80c2-41ca-af82-e9b41f1545e5)

![CleanShot 2024-10-09 at 11 59 30@2x](https://github.com/user-attachments/assets/029bfa2b-31ea-40f4-9f15-68a20fa3e0da)

2024-10-15 22:11 UTC, rodrigoareis commented on forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
> +    public ServerConfig getServerConfig() {
Add doc

2024-10-15 22:18 UTC, rodrigoareis requested changes
Just a minor comment to be addressed

2024-10-16 14:07 UTC, spetrov submitted a review, later dismissed
Looks good to me! 👍🏻

2024-10-16 16:10 UTC, witrisna commented on forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
> +    public ServerConfig getServerConfig() {
Updated.

2024-10-16 16:17 UTC, spetrov approved these changes

2024-10-16 16:17 UTC, merged